version: "3.7"
services:
  pylocker_db:
    image: postgres:13
    container_name: pylocker_db
    environment:
      POSTGRES_USER: "${PYLOCKER_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${PYLOCKER_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${PYLOCKER_POSTGRES_DB}"
      PG_DATA: "${PYLOCKER_PG_DATA}"
    ports:
      - "${PYLOCKER_DB_PORT}:5432"
    volumes:
      - "pylocker_data:${PYLOCKER_PG_DATA}"
    restart: unless-stopped
    networks:
      - pylocker_net

  fusionauth_db:
    image: postgres:13
    container_name: fusionauth_db
    environment:
      PGDATA: "${FUSIONAUTH_PG_DATA}"
      POSTGRES_USER: "${FUSIONAUTH_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${FUSIONAUTH_POSTGRES_PASSWORD}"
      POSTGRES_DB: "${FUSIONAUTH_POSTGRES_DB}"
    ports:
      - "${FUSIONAUTH_DB_PORT}:5432"
    restart: unless-stopped
    volumes:
      - "fusionauth_data:${FUSIONAUTH_PG_DATA}"
    networks:
      - pylocker_net

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - fusionauth_db
    environment:
      DATABASE_URL: "jdbc:postgresql://pylocker_net:5432/${FUSIONAUTH_POSTGRES_DB}"
      DATABASE_ROOT_USERNAME: "${FUSIONAUTH_POSTGRES_USER}"
      DATABASE_ROOT_PASSWORD: "${FUSIONAUTH_POSTGRES_PASSWORD}"
      DATABASE_USERNAME: "${FUSIONAUTH_POSTGRES_USER}"
      DATABASE_PASSWORD: "${FUSIONAUTH_POSTGRES_PASSWORD}"
      FUSIONAUTH_APP_MEMORY: 1G
      SEARCH_TYPE: database
      FUSIONAUTH_APP_URL: "${FUSIONAUTH_URL}"
    networks:
      - pylocker_net
    restart: unless-stopped
    ports:
      - "${FUSIONAUTH_PORT}:9011"
    volumes:
      - "fa_config:${FUSIONAUTH_CONFIG}"

  pylocker:
    container_name: pylocker
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pylocker_db
      - fusionauth
    ports:
      - "${APP_PORT}:9000"
    networks:
      - pylocker_net
    restart: unless-stopped

networks:
  pylocker_net:
    name: pylocker_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.52.0/24
volumes:
  pylocker_data:
  fusionauth_data:
  fa_config:
