version: "3.7"
services:
  auth_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      cluster.name: auth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    ports:
      - ${auth_es_http_interface_port}:9200
      - ${auth_es_communication_port}:9300
    networks:
      - auth_net
    restart: unless-stopped
    ulimits:
      memlock:
        soft: ${auth_es_memlock_soft}
        hard: ${auth_es_memlock_hard}
    volumes:
      - auth_data:/usr/share/elasticsearch/data

  auth_db:
    image: postgres:13
    environment:
      PGDATA: ${auth_db_data}
      POSTGRES_USER: ${auth_db_user}
      POSTGRES_PASSWORD: ${auth_db_password}
    ports:
      - ${auth_db_port}:5432
    networks:
      - auth_net
    restart: unless-stopped
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - auth_search
      - auth_db
    environment:
      SEARCH_SERVERS: ${auth_api_search_url}
      SEARCH_TYPE: ${auth_api_search_type}
      FUSIONAUTH_APP_MEMORY: ${auth_api_memory}
    networks:
      - auth_net
    restart: unless-stopped
    ports:
      - ${auth_api_port}:9011
networks:
  auth_net:
    name: auth_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24
volumes:
  auth_data:
  auth_db_data:
