"""basic setup

Revision ID: 08c1a41fe3ff
Revises: 
Create Date: 2020-12-15 21:43:40.898976

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08c1a41fe3ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('oid', postgresql.OID(), nullable=False),
                    sa.Column('owner_id', sa.TEXT(), nullable=True),
                    sa.Column('file_path', sa.TEXT(), nullable=True),
                    sa.Column('file_size_bytes', sa.INTEGER(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_path')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
