"""basic database structure

Revision ID: b7027a79aecd
Revises: 
Create Date: 2020-12-30 12:02:46.218986

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7027a79aecd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('oid', postgresql.OID(), nullable=False),
                    sa.Column('owner_id', sa.TEXT(), nullable=False),
                    sa.Column('file_path', sa.TEXT(), nullable=False),
                    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
                    sa.Column('file_checksum', sa.TEXT(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('owner_id', 'file_path', name='unique_paths_per_user')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
